In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print (torch.__version__)

2.0.1+cu118


In [2]:
 #introduction to tenses
 #PyTorch tensors are created using 'torch.Tensor()'

creating tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#matric
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [6,9,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [6, 9, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim
#dimension in the array

3

In [15]:
TENSOR.shape
#the shape of a tensor refers to the number of elements along each dimension of the tensor.

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [6, 9, 9],
        [2, 4, 5]])

In [17]:
TENSOR = torch.tensor([[[[2,3,3],
                        [6,9,9],
                         [4,5,6],
                       [2,4,5]]]])
TENSOR

tensor([[[[2, 3, 3],
          [6, 9, 9],
          [4, 5, 6],
          [2, 4, 5]]]])

In [18]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [19]:
TENSOR.ndim

4

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random nummbers to better represent the data.


start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [20]:
### create a Random Tensors of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6819, 0.7152, 0.6965, 0.4556],
        [0.8035, 0.0370, 0.0509, 0.8861],
        [0.9206, 0.2753, 0.2087, 0.2822]])

In [21]:
random_tensor.ndim

2

In [22]:
#create a random tensor with similar shape to an image tensor

In [23]:
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels(R , G , B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#creating a tensor of all ones
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [27]:
#Use torch.range()
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
one_to_ten = torch.arange(start=0 , end=1000 , step=99)
one_to_ten

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [30]:
#creating sensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes
Note:Tensor datatypes is one of the 3 big errors with PyTorch & deep learning
1. tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. tensors not right shape - to get shape from a tensor, can use tensor.shape
3. tensors not on the right devices - to get device from a tensor, can use tensor.device

In [31]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0 , 6.0 , 9.0],
                               dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_32_tensor.dtype

torch.float16

In [33]:
float_32_tensor = torch.tensor([3.0 , 6.0 , 9.0],
                               dtype=None, #what datatype is the tensor(e.g float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3,6,9] , dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

Attributes

In [41]:
#create a tensor
some_tensor = torch.rand(3,4) #functions
some_tensor

tensor([[0.9003, 0.2646, 0.6554, 0.8418],
        [0.6112, 0.8253, 0.3610, 0.4199],
        [0.2630, 0.8404, 0.9426, 0.1254]])

In [42]:
#find out details about some tensor
print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}") #attributes


tensor([[0.9003, 0.2646, 0.6554, 0.8418],
        [0.6112, 0.8253, 0.3610, 0.4199],
        [0.2630, 0.8404, 0.9426, 0.1254]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


##manipulating tensors(tensor operations)

Tensor operations include:


Addition
Substraction
Multiplication
Division
Matric multiplication

In [43]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [44]:
#multiply by 10
tensor * 10

tensor([10, 20, 30])

In [45]:
#division by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [46]:
#substract by 10
tensor - 10

tensor([-9, -8, -7])

1) the **inner dimensions** must match ;
(3,2) @ (3,2) wont work
(2,3) @ (3,2) will work
(3,2) @ (2,3) will work

2) the resulting matrix has the shape of the **outer dimensions**

In [47]:
#matrix multiplication
print(tensor , "*" , tensor)
print (f"equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals : tensor([1, 4, 9])


In [48]:
torch.matmul(tensor,tensor)

tensor(14)

one of the main errors - shapes

In [49]:
#to fix our tensor shape issues , we can manipulate the shape of one of our tensors using a transpose
# A TRANSPOSE switches the axes or dimensions of a given tensor.

In [50]:
# use tensor_B.T

In [51]:
tensor_A = torch.tensor (([1,2],
                          [3,4],
                          [5,6]))

tensor_B = torch.tensor (([7,10],
                          [8,11],
                          [9,12]))

torch.matmul(tensor_A , tensor_B)

RuntimeError: ignored

In [52]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [53]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [54]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [55]:
#the matrix multiplication operation works when tensor_b is transposed
print(f"original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New Shapes : tensor_A = {tensor_A.shape} (same shape as above) , tensor_B.T = { tensor_B.T.shape}")
print(f"Multiplying : {tensor_A.shape} @ {tensor_B.T.shape}")
print("output:\n")
output = torch.matmul(tensor_A , tensor_B.T)
print(output)
print(f"\noutput shape : {output.shape}")

original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New Shapes : tensor_A = torch.Size([3, 2]) (same shape as above) , tensor_B.T = torch.Size([2, 3])
Multiplying : torch.Size([3, 2]) @ torch.Size([2, 3])
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape : torch.Size([3, 3])


In [56]:
#finding the min, max , mean , sum , etc (tensor aggregation)
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
torch.min(x) , x.min()


(tensor(0), tensor(0))

In [ ]:
torch.max(x) , x.max()

In [59]:
torch.mean(x.type)

TypeError: ignored

In [60]:
#reshaping , stacking , squeezing and unsqueezing tensors


*Reshaping - reshapes an input tensor to a defined shape

*View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.

*Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

* squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimensions to a target tensor
* permute - return a view of the input with dimensions permuted (swapped) in a certain way.



In [61]:
#lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
#torch.squeeze()
x_reshaped.shape
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
#reproductibility (trying to take random out of random)

In short how a neutral network works:
start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ->

to reduce the randomness in neural networks and Pytorch comes the concept with RANDOM SEED .

Essentially what the random seed does is "flavour " the randomness.

In [67]:
torch.rand(3,3)

tensor([[0.2916, 0.9486, 0.1618],
        [0.3827, 0.9201, 0.0814],
        [0.4890, 0.8237, 0.2547]])

In [68]:
import torch

random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)


tensor([[0.2400, 0.6054, 0.3285, 0.1786],
        [0.8499, 0.7340, 0.7665, 0.1103],
        [0.0962, 0.1599, 0.6880, 0.9728]])
tensor([[0.3130, 0.8811, 0.5077, 0.6803],
        [0.2081, 0.1022, 0.1814, 0.2751],
        [0.1443, 0.3716, 0.2927, 0.9123]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [75]:
#lets make some random but reproducible tensors
import torch

#set the random seed
Random_seed = 99
torch.manual_seed(Random_seed)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(Random_seed)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.1033, 0.9702, 0.9481, 0.9787],
        [0.3268, 0.9200, 0.0503, 0.4583],
        [0.8608, 0.4882, 0.7981, 0.2011]])
tensor([[0.1033, 0.9702, 0.9481, 0.9787],
        [0.3268, 0.9200, 0.0503, 0.4583],
        [0.8608, 0.4882, 0.7981, 0.2011]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [76]:
#running tensors and pytorch objects on the GPUs ( an making faster computation)


GPUs = fatser computation on numbers , thank to CUDA + NVIDIA hardware + PyTorch working behind the scenes good.

In [ ]:
##getting a GPU
Easiest - use google colab for a free GPU


In [77]:
import torch
torch.cuda.is_available()


False