In [10]:
import tensorflow as tf
import numpy as np

In [11]:
X = tf.constant([[10, 7],
                      [7, 10],
                [3,4]])
Y = tf.constant([[9, 7],
                      [7, 9],
                 [4,5]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[9, 7],
        [7, 9],
        [4, 5]], dtype=int32)>)

In [12]:
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [ ]:
tf.reshape(Y , shape=(3 , 2))

In [ ]:
X.shape , tf.reshape(Y , shape=(2,3)).shape

In [13]:
#try to matrix multiply X by reshaped Y
X @ tf.reshape(Y , shape=(3 , 2))

InvalidArgumentError: ignored

In [15]:
tf.matmul(X , tf.reshape(Y , shape=(2 , 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[153,  98, 105],
       [153,  89,  99],
       [ 63,  37,  41]], dtype=int32)>

In [16]:
tf.matmul(tf.reshape(X , shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[167, 168],
       [127, 117]], dtype=int32)>

In [17]:
tf.reshape(X , shape = (2,3)).shape , Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [18]:
#try change the shape of X instead of Y
tf.matmul(tf.reshape(X , shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[167, 168],
       [127, 117]], dtype=int32)>

In [19]:
tf.transpose(X) , tf.reshape(X , shape=(2 , 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  3],
        [ 7, 10,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7,  7],
        [10,  3,  4]], dtype=int32)>)

In [20]:
#try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X) , Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[151, 148],
       [149, 159]], dtype=int32)>

The Dot Product

You can perform matrix multiplication using :
tf.matmul()
tf.tensordot()

In [21]:
#perform
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[9, 7],
        [7, 9],
        [4, 5]], dtype=int32)>)

In [22]:
tf.tensordot(tf.transpose(X) , Y , axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[151, 148],
       [149, 159]], dtype=int32)>

In [23]:
#perform matrix multiplication between X and Y
tf.matmul(X , tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[139, 133,  75],
       [133, 139,  78],
       [ 55,  57,  32]], dtype=int32)>

In [24]:
tf.matmul ( X , tf.reshape(Y , shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[153,  98, 105],
       [153,  89,  99],
       [ 63,  37,  41]], dtype=int32)>

In [25]:
#check the values of Y , reshape Y and transposed Y
print("Normal Y :")
print(Y , "\n")

print("Y reshaped to (2,3): ")
print(tf.reshape(Y , (2 ,3 )),"\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y :
tf.Tensor(
[[9 7]
 [7 9]
 [4 5]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[9 7 7]
 [9 4 5]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[9 7 4]
 [7 9 5]], shape=(2, 3), dtype=int32)


In [26]:
tf.matmul(X , tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[139, 133,  75],
       [133, 139,  78],
       [ 55,  57,  32]], dtype=int32)>

In [27]:
#changing the datatype of a tensor
B = tf.constant([1.7 , 7.4])
B.dtype

tf.float32

In [28]:
C = tf.constant([7 , 10])
C.dtype

tf.int32

In [29]:
#change from float32 to float16
D = tf.cast(B , dtype=tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [30]:
#aggregating tensors : condensing them from multiple values down to a smaller amount of values.
#get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [31]:
#get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

get the minimum


get the maximum


get the mean of a tensor


get the sum of a tensor



In [32]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([31, 47, 47, 78, 64, 60, 94, 16, 83,  8, 27, 94, 54, 54, 65, 23,  5,
       91, 24, 44, 18, 18, 67, 37, 53, 17,  1, 15, 77, 99,  5, 20,  9, 19,
       60, 42, 65, 98,  2, 84, 38, 53,  0, 78, 22, 28, 95,  1,  5, 80])>

In [33]:
tf.size(E) , E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [34]:
#find the min of tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [35]:
np.min(E)

0

In [36]:
#find the max
tf.reduce_max(E)


<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [37]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [38]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2215>

In [39]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=955>

In [40]:
#find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.914236>

In [41]:
#create a new tensor for finding positional minimum and maxmium
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [42]:
#find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [43]:
#index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [44]:
#find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [45]:
#check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

squeezing a tensor (removing all single dimensions )

In [46]:
#create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
          0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
          0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
          0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
          0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
          0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
          0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
          0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
          0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
          0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]],
      dtype=float32)>

In [48]:
G.shape

TensorShape([1, 1, 1, 50])

In [49]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]))

In [52]:
#one hot encoding
#create a list of indices
some_list = [0,1,2,3]  #could be red,green , blue,purple

#one hot encode our list of indices
tf.one_hot(some_list , depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [54]:
#specify custom values for one hot encoding
tf.one_hot(some_list , depth=4 ,on_value="yo i love deep learning" , off_value="i also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like to dance',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'yo i love deep learning',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'yo i love deep learning', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'i also like to dance', b'yo i love deep learning']],
      dtype=object)>

In [58]:
#squaring , log , square root
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [59]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [60]:
tf.sqrt(tf.cast(H , dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>